version: "3.8"

services:
  app:
    container_name: pbac_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - pbac_vol_app_ssh:/root/.ssh
      - pbac_vol_app_gh:/root/.config/gh
      - pbac_vol_app_go_mod_cache:/root/go/pkg/mod
    stdin_open: true # docker run -i
    tty: true # docker run -t

volumes:
  pbac_vol_app_ssh:
  pbac_vol_app_gh:
  pbac_vol_app_go_mod_cache:
