version: "3"

tasks:
  build:
    cmds:
      - task clean
      - task fmt
      - go build -o ./dist/permbac ./cmd/permbac/.

  exec:
    cmd: ./dist/permbac {{.CLI_ARGS}}

  run:
    cmds:
      - task build
      - ./dist/permbac {{.CLI_ARGS}}

  clean:
    cmds:
      - rm -rf ./dist

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  lint:
    cmd: golangci-lint run ./...

  test:
    cmds:
      - task fmt
      - task lint
      - go test ./...
