version: "3"

tasks:
  build:
    cmds:
      - task clean
      - task fmt
      - go build -o ./dist/arbac ./cmd/arbac/.

  exec:
    cmd: ./dist/arbac

  run:
    cmds:
      - task build
      - task exec

  clean:
    cmds:
      - rm -rf ./dist

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  lint:
    cmd: golangci-lint run ./...

  test:
    cmds:
      - task fmt
      - task lint
      - go test ./...
