version: "3"

tasks:
  build:
    cmds:
      - task clean
      - task fmt
      - go build -o ./dist/permbac ./cmd/permbac/.

  build-release:
    cmds:
      - task clean
      - task fmt
      - GOOS=linux GOARCH=amd64 go build -o ./dist/permbac-linux-amd64 ./cmd/permbac/.
      - GOOS=linux GOARCH=arm64 go build -o ./dist/permbac-linux-arm64 ./cmd/permbac/.
      - GOOS=darwin GOARCH=amd64 go build -o ./dist/permbac-darwin-amd64 ./cmd/permbac/.
      - GOOS=darwin GOARCH=arm64 go build -o ./dist/permbac-darwin-arm64 ./cmd/permbac/.
      - GOOS=windows GOARCH=amd64 go build -o ./dist/permbac-windows-amd64.exe ./cmd/permbac/.

  exec:
    cmd: ./dist/permbac {{.CLI_ARGS}}

  run:
    cmds:
      - task build
      - ./dist/permbac {{.CLI_ARGS}}

  clean:
    cmds:
      - rm -rf ./dist

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  lint:
    cmd: golangci-lint run ./...

  test:
    cmds:
      - task fmt
      - task lint
      - go test ./...
