name: Release tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
          cache: false

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Build
        run: task build-release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/permbac-linux-amd64
            ./dist/permbac-linux-arm64
            ./dist/permbac-darwin-amd64
            ./dist/permbac-darwin-arm64
            ./dist/permbac-windows-amd64.exe
